### ISSUE TITLE
Have to refresh page after entering channels to view streams on Firefox

### ISSUE THREAD

**Issue by Nocturnalizer** [EchoDev/TwitchHTML5#11]
Hi :)

I've noticed an issue with the Twitch HTML5 script using Firefox 45 x64. If I enter any channel on Twitch, 95% of the time the video won't load at all, nor will the controls. It'll just remain completely black. The chat will load fine. If I then refresh the page, the video will kick in after a few seconds as will the controls. I can reproduce most of the time. Is there any way to fix that?

Thanks for the help!

EDIT: Just to confirm, I don't have Flash installed and no other Twitch-related add-ons. The only add-ons I do have are Ublock Origin, RES and Greasemonkey. No other scripts installed other than yours.

**Comment by onetimesignup** [comment]
It's a problem with how twitch load their data (ajax control) which is often executed after the script already has been loaded but since the script has been updated with waitForKeyElements the needed amounts of refreshes should be a lot less than before.

The developer of the script (waitForKeyElements) however said that it may have to be tweaked to better fit twitch.

**Comment by EchoDev** [comment]
Have you updated to the latest version of the script? The latest version should improve reliability  greatly.

**Comment by Nocturnalizer** [comment]
It definitely seems quite a bit better since I updated to the latest version. I'll keep an eye on it but hoping this fixes it, though I know it's a difficult issue at the moment as you're working with an experimental stream. Really appreciate your work EchoDev, and thanks onetimesignup!

**Comment by EchoDev** [comment]
Great, I will be closing this issue for now.
