### ISSUE TITLE
Out of sync and stuttering issues lately

### ISSUE THREAD

**Issue by Nocturnalizer** [EchoDev/TwitchHTML5#14]
I've started to notice some issues with streams being out of sync with the audio, and also stuttering along with it. I'm guessing this is probably the HTML5 stream itself being experimental but I thought I'd mention it in case something in the script needs looking at. If there's any info I can give you let me know!

EDIT: I'm using the latest version of the script, 1.50 I believe. Using Firefox 44.0.2 x64. Tried with and without Better TTV and the issue remains. I've noticed that the spinning loading circle is continually going round and round to the left of the tab with the stream playing.

**Comment by onetimesignup** [comment]
I have a theory, do you run any form of adblocking? adblock+, ghostery or such ?

in short: I think it may be related to ads which are supposed to mute streams and then resume then once the ad is done and having the html5 running from within an iframe could mess things up, that or they just mess up the whole html5 player as-is with the ads, I haven't watched enough streams to confirm wether the iframe is relevant or not.

**Comment by SW1FT** [comment]
The HTML5 player doesn't run ads I think...

**Comment by Nocturnalizer** [comment]
@onetimesignup I do, although I always whitelist Twitch to support the streams. I use uBlock Origin and that's it. I've tested with it on and off and the issue is still there. It's definitely been happening over the past few days only.

**Comment by EchoDev** [comment]
My guess is that the HTML5 decoder inside browser are not intended for Streaming services. The desync issues tend to happen when there is high CPU usage, the audio keeps playing but the video stays behind. Because there is no sync check the stream starts desyncing. I guess the decoders still got a long way to go, I've also found issues when a stream stops and resumes, even though the browser keeps streaming video and audio files the output stays black.

It is something Twitch has to resolve with the browser makers and it is probably the reason Twitch hasn't "officially" released the HTML5 player.

**Comment by Nocturnalizer** [comment]
Things seem better today so I'm guessing it's as @EchoDev says. They're still fine-tuning the HTML5 stream so it's going through hiccups.

**Comment by EchoDev** [comment]
I will be closing this ticket for now. I'm 99% sure it is related to the decoders and browsers which we can't do anything about. The fix has to come from Google/Mozilla or Twitch.
