### ISSUE TITLE
Firefox's anti-tracking monitoring blocking the stream player

### ISSUE THREAD

**Issue by SW1FT** [EchoDev/TwitchHTML5#17]
Title is self-explanatory also, I'm running FF DE 46.0a2 on Windows 10.
The only way to actually see the stream is by disabling anti-tracking monitoring temporarily on Twitch or disabling it completely.

**Comment by onetimesignup** [comment]
Are you using the default (recommended) list or the strict one?

I'm using the default list on FF v44.0.2 (latest version on my end) for anti-tracking and I don't have any issues with twitch other than the 'mature streamer' confirmation button doesnt always show so I have to refresh till it pops up or otherwise the image wont load but I doubt it's related.

**Comment by SW1FT** [comment]
I'm using the recommended one list.

**Comment by AnAkkk** [comment]
Same here with default (recommended) list. FF 46.

**Comment by EchoDev** [comment]
https does indeed break the script. I had a problem a while ago with HTTPS Everywhere which enabled https on twitch a while ago. It breaks the video player. Not much to do about it unless Twitch fixes their problems with https, I'm not going to force a rewrite from http to https since Twitch doesn't seem to have SSL configured on their videostream domains and I don't feel it is right to force https to http. 

If people want protection from tracker I would recommend uBlock Origin, imo a much better solution for with minimal RAM and CPU usage.

**Comment by EchoDev** [comment]
I made the script HTTPS compatible. Seems like Twitch is also pushing HTTPS now. Dunno if your problems are fixed. Let me know!

**Comment by SW1FT** [comment]
Stream controls are there but the video is still black.

**Comment by EchoDev** [comment]
Did you try a full refresh with CTRL+F5? Streams are working fine here with Firefox 45 and the latest Greasemonkey.

**Comment by EchoDev** [comment]
If you have Firefox change the following:

security.mixed_content.block_active_content set to false

Firefox and Chrome do not allow http content on https sites unless you force it in the settings.

**Comment by EchoDev** [comment]
Allowing mixed content in your browser should fix this issue.
