### ISSUE TITLE
Mixed content

### ISSUE THREAD

**Issue by qwemaze** [EchoDev/TwitchHTML5#26]
Mixed Content: The page at 'https://player.twitch.tv/?branding=false&html5&quality=source&showInfo=false&channel=/etozhemad' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://video56.fra01.hls.ttvnw.net/hls-826088/etozhemad_20502709136_4264775…ame=video56.fra01,fmt=chunked&sig=27f5fd395bc43c604351180c73608071aec0d9ab'. This request has been blocked; the content must be served over HTTPS.

**Comment by EchoDev** [comment]
Twitch doesn't support HTTPS on stream domains, nothing we can do about except wait for Twitch to fix it.

You need to enable mixed content in your browser if you want to use this script.

**Comment by qwemaze** [comment]
Yeah you mentioned it in the README.md, but I've allowed "Insecure content" and still getting this error, so decided to submit an issue.

**Comment by EchoDev** [comment]
Are you using Chrome? The latest version has a bug which breaks mixed content. If you want it to work you need to wait for a new Chrome build or go to an older build (not recommended)

**Comment by qwemaze** [comment]
Thanks!

**Comment by onetimesignup** [comment]
@qwemaze 

the chrome solution until they've resolved the bug is to force the mode for the entire browser by launching it with additional arguments, modify your chrome shortcut to look something like this:
``"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --allow-running-insecure-content`
but use at your own risk
