### ISSUE TITLE
Theatre Mode

### ISSUE THREAD

**Issue by happygolucky919** [EchoDev/TwitchHTML5#5]
Twitch has moved the Theatre Mode button inside the video player next to the Fullscreen button. Can we get a fix for this?

**Comment by EchoDev** [comment]
Looking into it. I can get the button to appear but it doesn't seem to respond to clicks.

**Comment by EchoDev** [comment]
So....I kinda fixed it. I added a new "Theater mode" text button to the bottom of Twitch.

Why didn't I use the new button inside the player you say? Well...due to limitations with javascript it was not possible to use this button for the theater mode (This is due to the player being in an iframe.

Anyways, it is working again, enjoy!
